version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - gocritic
    - goconst
    - gocognit
    - mnd
  settings:
    mnd:
      ignored-numbers: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - mnd
          - gosec
          - gocritic
          - goconst
          - gocognit
          - gocyclo
    paths:
      - vendor

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - vendor
